import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.className} flex flex-col justify-center`}>
        <Header />
        <div className="h-2/3 flex justify-center items-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
